### ISSUE TITLE
Gamma Knife for Geant4

### ISSUE THREAD

**Issue by rcorredorj** [janpipek/g4application#20]
Dear Jan,

I contact you for asking a question about the Gamma Knife simulation code presented in your "A modular Geant4 model of Leksell Gamma Knife Perfexion™".

Reading the document you announce that,
"Although the above-mentioned features were developed primarily to support this particular model of LGK, they are general enough to be embodied into other medical Geant4 applications. The modular application code is freely available as open-source software under MIT licence and can be obtained from http://github.com/janpipek/g4application."
, however, the Gamma Knife section seems to be excluded in the version available online.

I would like to know if this section would be available online soon. I'm only searching for an approximate version to the LGK kernels (collimators 4mm, 8mm, 16mm) in order to test a  optimization method for treatment planning.

Thank you and have a good day,

--------------------------
Ricardo Corredor
Scientific Assistant

**Comment by janpipek** [comment]
Dear Ricardo,

this package is just the back-bone of the model - i.e. a general framework for writing applications with components and plugins in Geant4 (I hope this is consistent with what is written in the article). I want to publish also the Perfexion-related part but there are some issues preventing me from doing that (I will write you a personal e-mail regarding this).

Cheers,
Jan

**Comment by janpipek** [comment]
Closing the issue. Communication follows in private channel.
